# Generated by Django 2.2 on 2019-04-28 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklibrary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('pic', models.ImageField(upload_to='hotpic')),
            ],
        ),
    ]
