# Generated by Django 2.2 on 2019-04-17 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_stu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stu',
        ),
    ]
